---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность просматривать товары пользуясь постраничным выводом
  - Пользователь должен иметь возможность видеть название, рейтинг, цена со скидкой и без нее
  - Пользователь должен иметь возможность удалить товар из корзины и оформить заказ с переходом на страницу оплаты
non-functional:
  - Сайт должен разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную верси
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Сайт должен быть доступен на различных устройствах
  - Сайт должен не перезагружать страницу приложения
  - Сайт должен хранить корзину в сессии браузера
implicit:
  - Сайт должен иметь возможность перевода языка
  - Сайт должен уведомлять пользователей о появлении неожиданные проблемы/ошибки 
